version: "1"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - goconst
    - misspell
    - gocyclo
    - unparam

run:
  timeout: 5m
